2018-09-08 11:14:56,424 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:15:06,955 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:16:17,121 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:36:02,685 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:43:02,928 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:44:54,737 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:49:10,481 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:54:22,553 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-09 15:18:42,869 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:76]
2018-09-10 15:19:21,782 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:80]
2018-09-10 15:19:32,440 ERROR: Exception on /auth/login [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/app/auth/routes.py", line 32, in login
    return render_template('auth/login.html', title=_('登录'), form=form)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/login.html
2018-09-10 15:22:09,560 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:80]
2018-09-10 15:22:16,519 ERROR: Exception on /auth/login [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/app/auth/routes.py", line 32, in login
    return render_template('auth/login.html', title=_('登录'), form=form)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jpch89/code/microblog/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/jpch89/code/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/home/jpch89/code/microblog/app/templates/base.html", line 21, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('index') }}">{{ _('微博客') }}</a>
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-09-10 15:22:55,950 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:80]
